version: '2'
services:

  greet:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/greet-grpc-envoy.yaml:/etc/greet-grpc-envoy.yaml
    ports:
      - "5555:5555"
      - "9901:9901"
    expose:
      - "5555"
